language: rust
rust:
  - 1.25.0
  - stable
  - beta
  - nightly
cache: cargo
script:
    - cargo test --no-default-features --features "$FEATURES"
env:
    matrix:
        - FEATURES="bigint wtf8"
        - FEATURES=""
