[package]
name = "python-parser"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]
license = "GPL-3.0-or-later"

[dependencies]
nom = "^4.0"
nom_locate = "^0.1"

[dev-dependencies]
pretty_assertions = "^0.4"
