[package]
name = "python-parser"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]
license = "GPL-3.0-or-later"

[[bin]]
name = "prettyprint"
path = "src/main.rs"

[dependencies]
nom = "^4.0"
#nom_locate = { path = "../nom_locate/" }
nom_locate = { git = "https://github.com/ProgVal/nom_locate", branch = "nom4" }
unicode-xid = "^0.1"

[dev-dependencies]
pretty_assertions = "^0.4"
